language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt 
  - pip install coveralls codecov
  - pip install -r requirements.txt

script: 
  - coverage run --source app -m pytest
  - python -m coverage report -m
  - pytest --cov-report=term-missing --cov=app
    
after_success:
  - coveralls.
  - codecov --token=sXwfdtlmRegFW8mqAbUMjTVwkfloZ4iZE
