language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

before_script:
  - export APP_SECRET_KEY="something"
  - psql -c "CREATE DATABASE development;" -U postgres
  - psql -l;
  

script: 
  
  - coverage run --source app -m pytest
  - python -m coverage report -m
  
after_success:
  - coveralls