"""empty message

Revision ID: 536a10feeb9c
Revises: 102503c69673
Create Date: 2019-05-30 15:01:00.676661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '536a10feeb9c'
down_revision = '102503c69673'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('description', sa.String(length=255), nullable=True))
    op.drop_column('incidents', 'comment')
    op.drop_column('incidents', 'media')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('media', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('incidents', sa.Column('comment', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('incidents', 'description')
    # ### end Alembic commands ###
