"""empty message

Revision ID: b35557ca4c01
Revises: c5663ded458e
Create Date: 2019-05-27 10:45:25.643185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b35557ca4c01'
down_revision = 'c5663ded458e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
